version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uniform-frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - uniform-network

networks:
  uniform-network:
    external: true
